### ISSUE TITLE
Tridimensional Chunk System (Performance Boost)

### ISSUE THREAD

**Issue by linsaftw** [2lstudios-mc/MobStacker#4]
Tridimensional Chunk System allows for the server to save resources by "regionalizing" the load of the mob stacking system in small chunks and avoid lots of unnecessary checks to save CPU usage.

- Separate XYZ coordinates in sections of 16 blocks to generate tridimensional Chunks for checking entities inside.
- When a non player entity moves or spawns (Including by Chunk Load), it is added to the new TridimensionalChunk and removed from the old one (if exists).
- Chunk merging scheduler will be removed and merging will only action in the case an entity enters a new chunk.
- A configurable limit will be applied to entities moving to new Tridimensional Chunks if no merge took place. (When a mob is removed it will be added to the "removed mobs" count to show in the info command)
- When an Entity is despawned (Including by Chunk Unload), it will be removed from the Tridimensional Chunk.
- When no entities are inside a Tridimensional Chunk, it will be added to a remove queue to save resources.
- When an entity enters a Tridimensional Chunk, it will be removed from the remove queue.
- The Tridimensional Chunk remove queue will be executed each 15 seconds.

**Comment by iChocoMC** [comment]
**Separate XYZ coordinates in sections of 16 blocks to generate tridimensional Chunks for checking entities inside.**

El metodo getNearbyEntities() divide todo en chunks y solo te retorna las entidades que se encuentran en chunks cargados para evitar cargarlos y usar más cpu. El codigo es realmente eficiente, puedes verlo en nms. Ademas vi el codigo y veo que usas: 

entity.getChunk().getEntities();

Esto esta bien, pero hay entidades fuera de ese chunk que no podran ser stackeadas, considera cambiar el metodo.


**When a non player entity moves or spawns (Including by Chunk Load), it is added to the new TridimensionalChunk and removed from the old one (if exists).**

Esto me suena a pesado, el hacer un check para cada movimiento de entidad y revisar si se encuentra en otro chunk distinto no creo que sea de lo más eficiente, habra que ver como lo implementas xD.

**Chunk merging scheduler will be removed and merging will only action in the case an entity enters a new chunk.**

Si un jugador con alta velocidad carga muchos chunks entonces este sistema no sería eficiente porque tendria que hacer demasiados checks y stacks para 1 jugador. Imaginate si tenes 100.

**When an Entity is despawned (Including by Chunk Unload), it will be removed from the Tridimensional Chunk.
When no entities are inside a Tridimensional Chunk, it will be added to a remove queue to save resources.
When an entity enters a Tridimensional Chunk, it will be removed from the remove queue.
The Tridimensional Chunk remove queue will be executed each 15 seconds.**

Esto esta bien, pero me resulta extraño hacer todo un sistema re complejo para entidades cuando puedes hacer algo más o igual de eficiente sin todo esto. Pero bueno, habra que juzgar con el código hecho y no con ideas.

**Comment by linsaftw** [comment]
No se que tan eficiente sea el getNearbyEntities(), pero este metodo permite obtener las entidades alrededor con casi 0 impacto en el rendimiento, solo memory access que como maximo consumiran 0.6% con millones de mobs.

El sistema actual del codigo es completamente inviable y con rendimiento espantoso.

No es pesado lo del movimiento.

No conozco otra manera de hacerlo igual de eficiente.

**Comment by iChocoMC** [comment]
> No se que tan eficiente sea el getNearbyEntities(), pero este metodo permite obtener las entidades alrededor con casi 0 impacto en el rendimiento, solo memory access que como maximo consumiran 0.6% con millones de mobs.
> 
> El sistema actual del codigo es completamente inviable y con rendimiento espantoso.
> 
> No es pesado lo del movimiento. Los metodos pesados e iteracion solo se ejecutan cuando cambia el Tridimensional Chunk.
> 
> No conozco otra manera de hacerlo igual de eficiente.
> 
> Resumen: Estamos usando la memoria para guardar toda la informacion necesaria para realizar un stackeo de mobs, lo cual nos permite de forma optimizada realizar las busquedas y stackeo.

el getNearbyEntity() con una carga de chunks intensiva y con un test hecho en spark llego a usar 0.1%. Ademas del poco uso de ram, el uso de cpu no es tan elevado. Si quieres tener 2340 millones de entidades (cosa poco probable en servidores survival normales) este metodo se quedaria corto

**Comment by iChocoMC** [comment]
Si tu metodo llega a usar tan poco cpu, sería de locos xD. Pero hay que ver el tema de ram, la mayoría de server "comunes" tienen una cpu decente y muy poca ram.

**Comment by linsaftw** [comment]
> Si tu metodo llega a usar tan poco cpu, sería de locos xD. Pero hay que ver el tema de ram, la mayoría de server "comunes" tienen una cpu decente y muy poca ram. Mira las paginas que dan hosting de minecraft, es muy cara la ram y el cpu es decente.

Para eso esta el sistema que auto elimina los chunks tridimensionales.

**Comment by linsaftw** [comment]
Done.
